version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/packages/*'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/api/*'
    schedule:
      interval: 'monthly'
